# Changes here will be overwritten by Copier
_commit: d56cb12
_src_path: https://github.com/python-project-templates/base.git
add_extension: python
email: t.paine154@gmail.com
github: airflow-laminar
project_description: Pydantic models for supervisor
project_name: supervisor-pydantic
python_version_primary: '3.11'
team: the supervisor-pydantic authors
